In [1]:
import re

text = "I love playing football! It's amazing 😍 #AI"

# Step 1: lowercase
text = text.lower()

# Step 2: remove special characters (keep words)
text = re.sub(r"[^a-zA-Z0-9\s]", "", text)

# Step 3: split
tokens = text.split()

print(tokens)

['i', 'love', 'playing', 'football', 'its', 'amazing', 'ai']


In [ ]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uscased")

text = "I love playing football yash deliwala loves ai and ai coding"

tokens = tokenizer.tokenize(text)
token_ids = tokenizer.convert_tokens_to_ids(tokens)

print("Tokens:", tokens)
print("Token IDs:", token_ids)

d:\Desktop\ai-projects\.venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\admin\.cache\huggingface\hub\models--bert-base-cased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)


Tokens: ['I', 'love', 'playing', 'football', 'ya', '##sh', 'del', '##i', '##wala', 'loves', 'a', '##i', 'and', 'a', '##i', 'coding']
Token IDs: [146, 1567, 1773, 1709, 11078, 2737, 3687, 1182, 27222, 7871, 170, 1182, 1105, 170, 1182, 19350]


In [11]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

text = "ChatGPT is mindblowing123"

tokens = tokenizer.tokenize(text)
token_ids = tokenizer.convert_tokens_to_ids(tokens)

print("Tokens:", tokens)
print("Token IDs:", token_ids)

Tokens: ['chat', '##gp', '##t', 'is', 'mind', '##bl', '##owing', '##12', '##3']
Token IDs: [11834, 21600, 2102, 2003, 2568, 16558, 14138, 12521, 2509]


In [34]:
from transformers import AutoTokenizer, AutoModel
import torch

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

text = "AI is powerful how r u we yash deliwala go to bank.chat gpt is best.clause is best."

inputs = tokenizer(text, return_tensors="pt")
outputs = model(**inputs)
tokens = tokenizer.tokenize(text)
print(tokens)
print(len(tokens))

print(tokens[3])  # some word
print(outputs.last_hidden_state[0][3])

print(outputs.last_hidden_state.shape)


tokens_full = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])

for i, token in enumerate(tokens_full):
    print(i, token)

Loading weights: 100%|██████████| 199/199 [00:00<00:00, 8485.83it/s]
BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.


['ai', 'is', 'powerful', 'how', 'r', 'u', 'we', 'ya', '##sh', 'del', '##i', '##wala', 'go', 'to', 'bank', '.', 'chat', 'gp', '##t', 'is', 'best', '.', 'clause', 'is', 'best', '.']
26
how
tensor([ 1.3765e-01, -4.7246e-01,  2.5373e-02, -1.5030e-02,  2.6124e-01,
        -1.2171e-01,  3.9733e-01, -2.4041e-01, -1.6203e-01, -5.9304e-01,
         2.8082e-01,  2.5999e-01,  2.3151e-01,  1.1519e-01, -5.1953e-01,
         1.3445e-01,  1.4944e-01, -3.2690e-01, -4.8877e-01,  1.9510e-02,
        -1.3894e-01,  2.3904e-01,  6.1815e-02,  4.4426e-01,  2.2471e-01,
         3.9225e-02, -1.9154e-01,  4.4051e-01, -9.8681e-02, -3.7803e-01,
         5.1556e-01,  5.0933e-01, -7.3581e-02,  1.2030e-01, -5.3258e-01,
        -6.4987e-01, -8.2041e-02,  2.6751e-01, -5.5496e-01,  1.1507e-02,
        -3.9392e-01, -6.5170e-01,  2.6085e-01,  4.2819e-01, -1.9821e-01,
        -3.0149e-01, -4.8652e-01,  5.2001e-01,  6.3516e-01, -2.1225e-01,
        -6.8729e-01,  3.6371e-02, -1.7884e-01, -1.5068e-01, -1.1626e-01,
         7

In [35]:
import torch
import torch.nn as nn

# Example sentence: 5 words, each word = 10 features
x = torch.randn(1, 5, 10)  
# [batch, sequence_length, input_size]

lstm = nn.LSTM(input_size=10, hidden_size=20, batch_first=True)

output, (h_n, c_n) = lstm(x)

print("Output shape:", output.shape)
print("Hidden state shape:", h_n.shape)

Output shape: torch.Size([1, 5, 20])
Hidden state shape: torch.Size([1, 1, 20])


In [36]:
import torch
import torch.nn.functional as F

# pretend 3 words, each has 4 features
x = torch.randn(3, 4)

# similarity (who relates to whom)
scores = torch.matmul(x, x.T)

# convert to probabilities
weights = F.softmax(scores, dim=1)

# weighted sum
output = torch.matmul(weights, x)

print("Attention Weights:\n", weights)
print("Output:\n", output)

Attention Weights:
 tensor([[7.2275e-01, 4.6305e-02, 2.3095e-01],
        [8.7737e-05, 9.9986e-01, 4.7301e-05],
        [3.9073e-02, 4.2236e-03, 9.5670e-01]])
Output:
 tensor([[ 0.4694, -0.3290, -1.1699, -0.1737],
        [ 1.7941, -1.2288,  0.9889,  1.7675],
        [-0.7348, -0.9347, -1.5673,  0.3739]])
